Updated bin/tomcat

diff --git a/bin/tomcat b/bin/tomcat
--- a/bin/tomcat
+++ b/bin/tomcat
@@ -3,7 +3,7 @@
 # ------------------------------------------
 #
 # Created by Statemood, 2012.12.06 18:00
-# Updated by Statemood, 2012.12.08 17:00
+# Updated by Statemood, 2012.12.10 14:30
 #            Statemood@gmail.com
 #
 # ------------------------------------------
@@ -13,6 +13,7 @@ APP_NAME="$1"
 APP_PATH=/data/www
 APP_LOGS=$APP_PATH/$APP_NAME/logs/catalina.out
 ARGUMENT="$2"
+ERRORMSG='\033[1;41mError\033[0m'
 
 sucmd(){
     su - "$1" -c "$2"
@@ -22,6 +23,11 @@ Getid(){
     APP_PIDS=`ps aux | grep "$1" | egrep -v "grep $1|$0" | awk '{print $2}'`
 }
 catalinaout(){
+    if [ ! -f "$APP_LOGS" ]
+    then
+        echo -e "$ERRORMSG: '$APP_LOGS': File not found"
+        exit 1
+    fi
     Tailines="$1"
     if [ -z "$Tailines" ]
     then
@@ -35,26 +41,32 @@ start(){
     Getid "$APP_NAME"
     if [ ! -z "$APP_PIDS" ]
     then
-        echo -e "Error: $APP_NAME already running with PID $APP_PIDS"
+        echo -e "$ERRORMSG: $APP_NAME already running with PID $APP_PIDS"
         exit 1
     fi
     sucmd "$RUN_USER" "cd $APP_PATH/$APP_NAME/bin;./startup.sh > /dev/null 2>&1"
     Getid "$APP_NAME"
     if [ -z "$APP_PIDS" ]
     then
-        echo -e "\033[1;31mfailed\033[0m"
+        printf "\033[1;31m%16s\033[0m\n" "failed" 
     else
-        echo -e "\033[1;33mdone\033[0m"
+        printf ": PID %-8s\033[1;33m%16s\033[0m\n" "$APP_PIDS" "done" 
     fi
 }
 
 stop(){
     printf "Tomcat stopping \033[1m%-16s\033[0m" "$APP_NAME"
     Getid "$APP_NAME"
+    KILLEDPID=$APP_PIDS
     if [ -z "$APP_PIDS" -a "$ARGUMENT" != "restart" ]
     then
-        echo -e "Error: $APP_NAME not running"
+        echo -e "$ERRORMSG: $APP_NAME not running"
         exit 1
+    else
+        if [ -z "$APP_PIDS" ]
+        then
+            NOT_RUN=1
+        fi
     fi
     sucmd "$RUN_USER" "$APP_PATH/$APP_NAME/bin/shutdown.sh > /dev/null 2>&1"
     sleep 1
@@ -66,7 +78,12 @@ stop(){
     Getid "$APP_NAME"
     if [ -z "$APP_PIDS" ]
     then
-        echo -e "\033[1;33mdone\033[0m"
+        if [ "$NOT_RUN" = 1 ]
+        then
+            printf ": Not running\n"
+        else
+            printf ": PID %-8s\033[1;33m%16s\033[0m\n" "$KILLEDPID" "done"
+        fi
     else
         echo -e "\033[1;31mfailed\033[0m"
     fi
@@ -86,7 +103,7 @@ status(){
 
 case "$2" in
     log)
-        catalinaout "$1"
+        catalinaout "$3"
         ;;
     stop)
         stop
